### ISSUE TITLE
Enabling 1280x720 resolution

### ISSUE THREAD

**Issue by D49ll** [nooway077/HoloLens2CVExperiments#1]
Hi,

First of let me say what a great repo this is! I'm using it for my master thesis in computervision.

I've added CameraUtils.MediaCaptureProfiles.HL2_1280x720 to the enum for CameraUtils. However cant seem to instantiate the camera with this resolution. Any suggestions on how to fix this?

I'm also curios if there is a method of changing the intrinsic matrix permanently on the hololens 2? The reason i'm asking is that i'm using a rather large framework for the visualization part with no option of setting this.

**Comment by nooway077** [comment]
Hey,
Thanks for the great words!  I don't have the HL2 anymore, but I will try to help you.

So, I've only tested the **896x504** and **2272x1278** resolutions for OpenCV and the latter one was painfully slow (more like unusable) so I sticked to the **896x504** doing my experiments.

You said that you've added the `HL2_1280x720` to the **CameraUtils.MediaCaptureProfiles** enum, but I would like to ask did you also add it to the `switch (mediaCaptureProfile)` inside **ArUcoTracking.cs** file at **line 67**? 

Like for example: 
```
case CameraUtils.MediaCaptureProfiles.HL2_1280x720:
        width = 1280;
        height = 720;
        break;
```

Then if you select it in **ArUcoTracking** script's properties from the Unity Editor, it should start with that resolution but I can't test it now.

As for the second question, I'm a bit confused about what you mean about permanently changing the calibration parameters for the HL2. The calibration procedure has to be performed only once per camera and then you need to input the computed values inside the corresponding field of the **ArUcoTracking** script's properties. According to the documentations, the HL2 also has built in intrinsics that are factory calibrated which should be pretty accurate, however I could not get those to work. (see **line 173** of the **ArUcoTracking.cs**)

Let me know if these help you.

**Comment by D49ll** [comment]
Thanks for your reply, and thanks for trying to help me :)

I'll try to specify a bit more in detail. 

So I want to calibrate / find the intrinsic matrix for the depth camera, as well as the right and left camera. The reasoning for this is that i'm trying to improve a hand-eye-calibration for my hololens which uses external optical tracking system.

The hololens program currently samples the charuco board in the hand-eye-calibration-metode with the resolution of 1280x720; so I would like to use your CameraCalibration with said resolution. This is what i've changed in your source code.

CameraCalibration.cs
```c#
            switch (mediaCaptureProfile)
            {
                case CameraUtils.MediaCaptureProfiles.HL2_2272x1278:
                    _imageWidth = 2272;
                    _imageHeight = 1278;
                    break;
                case CameraUtils.MediaCaptureProfiles.HL2_896x504:
                    _imageWidth = 896;
                    _imageHeight = 504;
                    break;
                case CameraUtils.MediaCaptureProfiles.HL2_1280x720:
                    _imageWidth = 1280;
                    _imageHeight = 720;
                    break;

                default:
                    _imageWidth = 0;
                    _imageHeight = 0;
                    break;
            }
``` 

CameraUtils.cs
```c#
public enum MediaCaptureProfiles
{
    HL2_2272x1278,
    HL2_896x504,
    HL2_1280x720,
}
``` 

However, after building and deploying this solution successfully i get the following error when trying to initialize the PV with 1280x720 resolution

```c#
Failed to start camera: Sequence contains no matching element
``` 

I think this error is from the following try-catch block:

CameraCalibration.cs
```c#
            try
            {
                _tcpClient = GetComponent<TCPClient>();
                _tcpClient.ConnectToServerEvent();

                _mediaCapturer = new MediaCapturer();
                await _mediaCapturer.StartCapture(_imageWidth, _imageHeight, frameRate);

                HUD.text = "Camera started. Running!";
            }
            catch (Exception ex)
            {
                HUD.text = "Failed to start camera: " + ex.Message;
            }

``` 
As for the second question I was just wondering if i could change the intrinsic matrix for the camera, but after reading the code for ArUcoTracking I've concluded with that not being the case. You rather choose either to use Hololens' own intrinsic matrix or the new calibrated one. This means that i need to change my program to choose in the same manner. 


Regarding this 
```
According to the documentations, the HL2 also has built in intrinsics that are factory calibrated which should be pretty accurate, however I could not get those to work.
``` 

What do you mean you did not get it to work? Did "var pFIntrinsics = mediaFrameReference?.VideoMediaFrame?.CameraIntrinsics;" not return any values?

**Comment by nooway077** [comment]
Right, 
So I suspect the issue was with **line 144** of the `MediaCapturer.cs` file. Now as I mentioned, I don't have the device at the moment so I can't test my solution, but I've commited the changes to the repo which could resolve this issue. The project runs inside the emulator with **HL2_1280x720** settings. It was able to start the emulated camera (which is blank but it does not crash), however I'm not sure how exactly the emulator handles the `mediacapture`, which means it might still crash on a physical device.

After reading through your reply, I would like to suggest another approach which could be easier: since you only need the calibration matrix, you could take pictures or record video from **Device Portal** by turning off everything except the PV camera. Then you could run **opencv** on those files to calculate the intrinsics for the camera similar to what I did in [Calibrate_PhotoVideo.py](https://github.com/nooway077/HoloLens2CVExperiments/blob/main/aruco-pose-estimation/utilities/Calibrate_PhotoVideo.py). This is basically what the **CameraCalibration Scene** is for, it just sends the frames to a PC and then they can be processed with the corresponding python utility script.

As for finding the intrinsics for the **depth camera**, as well as the **right** and **left** camera, you'll need to use the [research mode project](https://github.com/nooway077/HoloLens2CVExperiments/tree/main/aruco-pose-estimation/projects/researchmode/HoloLens2CVResModeUnity), but I did not implement the required functions for the **depth camera**, it only has support for the **Front Facing VLC cameras** which you have probably meant by the left and right camera.

> Did "var pFIntrinsics = mediaFrameReference?.VideoMediaFrame?.CameraIntrinsics;" not return any values? 

Exactly, as you can see inside the **ArUcoTracking.cs** at **line 173** if I tried to use their values it immediately threw **NullReferenceException**, which could be because it doesn't always return the intrinsics for each frame. I instead went with the manual calibration route and created the CameraCalibration scene & the python scripts to compute the matrices.
